// ALL LOGIC GATES ARE BUILT BY PAIRS OF NMOS AND PMOS TRANSISTORS, AND GATES ARE THE BUILDING BLOCKS OF ALL DIGIAL DEVICES FROM SIMPLE TO COMPLEX

// SOFTWARE IS JUST ELECTRON FLOW

// FORGET LOGIC, THINK IN ELECTRON FLOW